/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.systemadmin;

import business.Business;
import business.email.SendEmail;
import business.enterprise.Enterprise;
import business.workarea.NewEnterpriseWorkRequest;
import business.workarea.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pu
 */
public class ManageNewEnterpriseRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageNewEnterpriseRequestJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    private NewEnterpriseWorkRequest request;

    public ManageNewEnterpriseRequestJPanel(JPanel userProcessContainer, Business business, NewEnterpriseWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.request = request;
        populateFields();
    }

    public void populateFields() {
        requestedNetworkJTextField.setText(request.getNetwork().getNetworkName());
        enterpriseTypeJTextField.setText(request.getEnterpriseType().getValue());
        firstNameJTextField.setText(request.getPerson().getFirstName());
        lastNameJTextField.setText(request.getPerson().getLastName());
        businessEmailIdJTextField.setText(request.getPerson().getContact().getEmailId());
        businessPhoneJTextField.setText(request.getPerson().getContact().getPrimaryPhoneNumber());
        cityJTextField.setText(request.getPerson().getAddress().getCity());
        messageJTextField.setText(request.getMessage());
        stateJTextField.setText(request.getPerson().getAddress().getState());
        addressJTextField.setText(request.getPerson().getAddress().getStreet());
        countryJTextField.setText(request.getPerson().getAddress().getCountry());
        businessDescriptionJTextArea.setText(request.getDescription());
        businessNameJTextField.setText(request.getEnterpriseName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        requestedNetworkJTextField = new javax.swing.JTextField();
        enterpriseTypeJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        approveJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblBusinessPhone1 = new javax.swing.JLabel();
        businessEmailIdJTextField = new javax.swing.JTextField();
        lblBusinessCountry1 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        businessPhoneJTextField = new javax.swing.JTextField();
        firstNameJTextField = new javax.swing.JTextField();
        lblLastName1 = new javax.swing.JLabel();
        lastNameJTextField = new javax.swing.JTextField();
        lblBusinessState1 = new javax.swing.JLabel();
        lblAddressLine3 = new javax.swing.JLabel();
        lblFirstName1 = new javax.swing.JLabel();
        businessNameJTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        businessDescriptionJTextArea = new javax.swing.JTextArea();
        lblBusinessName1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cityJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblBusinessEmailId3 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        lblBusinessCity1 = new javax.swing.JLabel();
        stateJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        countryJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Network Requested:");

        requestedNetworkJTextField.setEnabled(false);

        enterpriseTypeJTextField.setEnabled(false);

        jLabel3.setText("Enterprise Type:");

        approveJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        approveJButton.setText("Approve");
        approveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Business Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBusinessPhone1.setText("Business Phone:");
        jPanel1.add(lblBusinessPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        businessEmailIdJTextField.setEnabled(false);
        businessEmailIdJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(businessEmailIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        lblBusinessCountry1.setText("Country:");
        jPanel1.add(lblBusinessCountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        addressJTextField.setEnabled(false);
        addressJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        businessPhoneJTextField.setEnabled(false);
        businessPhoneJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(businessPhoneJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        firstNameJTextField.setEnabled(false);
        firstNameJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(firstNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        lblLastName1.setText("Last Name:");
        jPanel1.add(lblLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lastNameJTextField.setEnabled(false);
        lastNameJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(lastNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        lblBusinessState1.setText("State:");
        jPanel1.add(lblBusinessState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        lblAddressLine3.setText("Street Address:");
        jPanel1.add(lblAddressLine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        lblFirstName1.setText("First Name:");
        jPanel1.add(lblFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        businessNameJTextField.setEnabled(false);
        businessNameJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(businessNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        businessDescriptionJTextArea.setColumns(20);
        businessDescriptionJTextArea.setRows(5);
        businessDescriptionJTextArea.setEnabled(false);
        jScrollPane4.setViewportView(businessDescriptionJTextArea);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 440, 70));

        lblBusinessName1.setText("Business Name:");
        jPanel1.add(lblBusinessName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 560, -1));

        cityJTextField.setEnabled(false);
        cityJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(cityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jLabel9.setText("Business Description and Domain:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        lblBusinessEmailId3.setText("Business Email Id:");
        jPanel1.add(lblBusinessEmailId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        messageJTextField.setEnabled(false);
        messageJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        lblBusinessCity1.setText("City:");
        jPanel1.add(lblBusinessCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        stateJTextField.setEnabled(false);
        stateJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(stateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabel5.setText("Message:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        countryJTextField.setEnabled(false);
        countryJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(countryJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Request Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(190, 190, 190)
                                .addComponent(approveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(requestedNetworkJTextField)
                            .addComponent(enterpriseTypeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestedNetworkJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseTypeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void approveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButtonActionPerformed
        // TODO add your handling code here:
        request.setStatus(WorkRequest.StatusType.Approved.getValue());
        Enterprise enterprise = request.getNetwork().getEnterpriseDirectory().createEnterprise(request.getEnterpriseName(), request.getEnterpriseType());
        String recep = request.getPerson().getContact().getEmailId();
        String sub = "Enterprise Approval";
        String username = request.getEnterpriseName();
        String password = request.getEnterpriseName() +"1234";
        SendEmail.SendEmail(recep, sub, username, password);
        JOptionPane.showMessageDialog(null, "Enterprise approved and Added successfully");
    }//GEN-LAST:event_approveJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton approveJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextArea businessDescriptionJTextArea;
    private javax.swing.JTextField businessEmailIdJTextField;
    private javax.swing.JTextField businessNameJTextField;
    private javax.swing.JTextField businessPhoneJTextField;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JTextField countryJTextField;
    private javax.swing.JTextField enterpriseTypeJTextField;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JLabel lblAddressLine3;
    private javax.swing.JLabel lblBusinessCity1;
    private javax.swing.JLabel lblBusinessCountry1;
    private javax.swing.JLabel lblBusinessEmailId3;
    private javax.swing.JLabel lblBusinessName1;
    private javax.swing.JLabel lblBusinessPhone1;
    private javax.swing.JLabel lblBusinessState1;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTextField requestedNetworkJTextField;
    private javax.swing.JTextField stateJTextField;
    // End of variables declaration//GEN-END:variables
}
