/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.systemadmin;

import business.Business;
import business.enterprise.Enterprise;
import business.network.Network;
import business.personinfo.Address;
import business.personinfo.Contact;
import business.personinfo.Person;
import business.utility.ValidatingFields;
import business.workarea.NewEnterpriseWorkRequest;
import business.workarea.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pu
 */
public class NewEnterpriseRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewEnterpriseRequestJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    private Network selectedNetwork = null;

    public NewEnterpriseRequestJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populateNetworkComboBox();
    }

    private void populateNetworkComboBox() {
        networkJComboBox.removeAllItems();

        for (Network network : business.getSystemOrganization().getNetwork().getNetworkDirectory().getNetworks()) {
            networkJComboBox.addItem(network);
        }

    }

    private void populateEnterpriseComboBox(Network network) {
        enterpriseTypeJComboBox.removeAllItems();

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            if (!type.equals(Enterprise.EnterpriseType.Distributor)) {
                enterpriseTypeJComboBox.addItem(type);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submitRequestJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        closeJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblBusinessPhone1 = new javax.swing.JLabel();
        businessEmailIdJTextField = new javax.swing.JTextField();
        lblBusinessCountry1 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        businessPhoneJTextField = new javax.swing.JTextField();
        firstNameJTextField = new javax.swing.JTextField();
        lblLastName1 = new javax.swing.JLabel();
        lastNameJTextField = new javax.swing.JTextField();
        lblBusinessState1 = new javax.swing.JLabel();
        lblAddressLine3 = new javax.swing.JLabel();
        lblFirstName1 = new javax.swing.JLabel();
        businessNameJTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        businessDescriptionJTextArea = new javax.swing.JTextArea();
        lblBusinessName1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cityJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblBusinessEmailId3 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        lblBusinessCity1 = new javax.swing.JLabel();
        stateJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        countryJTextField = new javax.swing.JTextField();
        errorLastNameJLabel = new javax.swing.JLabel();
        errorMessageJLabel = new javax.swing.JLabel();
        errorFirstNameJLabel = new javax.swing.JLabel();
        errorBussinessNameJLabel = new javax.swing.JLabel();
        errorPhoneJLabel = new javax.swing.JLabel();
        errorEmailIdJLabel = new javax.swing.JLabel();
        errorDescriptionJLabel = new javax.swing.JLabel();
        errorAddressJLabel = new javax.swing.JLabel();
        errorCityJLabel = new javax.swing.JLabel();
        errorStateJLabel = new javax.swing.JLabel();
        errorCountryJLabel = new javax.swing.JLabel();
        errorNetworkJLabel = new javax.swing.JLabel();
        errorEnterpriseJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Network:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("New Enterprise Request");

        submitRequestJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submitRequestJButton.setText("Submit Request");
        submitRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRequestJButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Enterprise Type:");

        enterpriseTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseTypeJComboBoxActionPerformed(evt);
            }
        });

        closeJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeJButton.setText("Close");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Business Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBusinessPhone1.setText("Business Phone:");
        jPanel1.add(lblBusinessPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        businessEmailIdJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(businessEmailIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        lblBusinessCountry1.setText("Country:");
        jPanel1.add(lblBusinessCountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        addressJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        businessPhoneJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(businessPhoneJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        firstNameJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(firstNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        lblLastName1.setText("Last Name:");
        jPanel1.add(lblLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lastNameJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(lastNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        lblBusinessState1.setText("State:");
        jPanel1.add(lblBusinessState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        lblAddressLine3.setText("Street Address:");
        jPanel1.add(lblAddressLine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        lblFirstName1.setText("First Name:");
        jPanel1.add(lblFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        businessNameJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(businessNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        businessDescriptionJTextArea.setColumns(20);
        businessDescriptionJTextArea.setRows(5);
        jScrollPane4.setViewportView(businessDescriptionJTextArea);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 440, 70));

        lblBusinessName1.setText("Business Name:");
        jPanel1.add(lblBusinessName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 560, -1));

        cityJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(cityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jLabel9.setText("Business Description and Domain:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        lblBusinessEmailId3.setText("Business Email Id:");
        jPanel1.add(lblBusinessEmailId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        messageJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        lblBusinessCity1.setText("City:");
        jPanel1.add(lblBusinessCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        stateJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(stateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabel3.setText("Message:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        countryJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(countryJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        errorLastNameJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorLastNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 140, 20));

        errorMessageJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorMessageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 140, 20));

        errorFirstNameJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorFirstNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 140, 20));

        errorBussinessNameJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorBussinessNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 140, 20));

        errorPhoneJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorPhoneJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 140, 20));

        errorEmailIdJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorEmailIdJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 140, 20));

        errorDescriptionJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorDescriptionJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 140, 20));

        errorAddressJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorAddressJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 140, 20));

        errorCityJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorCityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 140, 20));

        errorStateJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorStateJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 140, 20));

        errorCountryJLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(errorCountryJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 140, 20));

        errorNetworkJLabel.setForeground(new java.awt.Color(204, 0, 0));

        errorEnterpriseJLabel.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(networkJComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterpriseTypeJComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorEnterpriseJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorNetworkJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addComponent(submitRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorNetworkJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enterpriseTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorEnterpriseJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
        if (networkJComboBox.getSelectedIndex() != -1) {
            populateEnterpriseComboBox((Network) networkJComboBox.getSelectedItem());
        }
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void submitRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRequestJButtonActionPerformed
        // TODO add your handling code here:
        if (validateFormFields()) {
            try{
            WorkRequest workRequest = business.getSystemOrganization().getWorkQueue().createWorkRequest(WorkRequest.WorkRequestType.NewEnterpriseWorkRequestType.getValue());
            NewEnterpriseWorkRequest newEnterpriseRequest = (NewEnterpriseWorkRequest) workRequest;
            fillFormData(newEnterpriseRequest);
            JOptionPane.showMessageDialog(null, "Requested submitted.");            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Something went wrong.");
            }
        }
    }//GEN-LAST:event_submitRequestJButtonActionPerformed

    private void enterpriseTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseTypeJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseTypeJComboBoxActionPerformed

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_closeJButtonActionPerformed

    public boolean validateFormFields() {
        boolean isValid = true;
        if (ValidatingFields.isComboBoxValid(networkJComboBox)) {
            errorNetworkJLabel.setText("Select network.");
            isValid = false;
        } else {
            errorNetworkJLabel.setText("");
        }

        if (ValidatingFields.isComboBoxValid(enterpriseTypeJComboBox)) {
            errorEnterpriseJLabel.setText("Select enterprise.");
            isValid = false;
        } else {
            errorEnterpriseJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(firstNameJTextField)) {
            errorFirstNameJLabel.setText("Invalid first name.");
            isValid = false;
        } else {
            errorFirstNameJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(lastNameJTextField)) {
            errorLastNameJLabel.setText("Invalid last name.");
            isValid = false;
        } else {
            errorLastNameJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(businessNameJTextField)) {
            errorBussinessNameJLabel.setText("Invalid business name.");
            isValid = false;
        } else {
            Network network = (Network) networkJComboBox.getSelectedItem();
            if (network.getEnterpriseDirectory().isOrganizationNamePresent(businessNameJTextField.getText().trim())) {
                errorBussinessNameJLabel.setText("Business name already exist.");
                isValid = false;
            } else {
                errorBussinessNameJLabel.setText("");
            }           
        }

        if (ValidatingFields.isPhoneNoTextFieldValid(businessPhoneJTextField)) {
            errorPhoneJLabel.setText("Invalid phone number.");
            isValid = false;
        } else {
            errorPhoneJLabel.setText("");
        }

        if (ValidatingFields.isEmailIdTextFieldValid(businessEmailIdJTextField)) {
            errorEmailIdJLabel.setText("Invalid Email Id.");
            isValid = false;
        } else {
            errorEmailIdJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(businessDescriptionJTextArea)) {
            errorDescriptionJLabel.setText("Invalid value.");
            isValid = false;
        } else {
            errorDescriptionJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(addressJTextField)) {
            errorAddressJLabel.setText("Invalid user name.");
            isValid = false;
        } else {
            errorAddressJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(cityJTextField)) {
            errorCityJLabel.setText("Invalid value.");
            isValid = false;
        } else {
            errorCityJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(stateJTextField)) {
            errorStateJLabel.setText("Invalid state value.");
            isValid = false;
        } else {
            errorStateJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(countryJTextField)) {
            errorCountryJLabel.setText("Invalid country value.");
            isValid = false;
        } else {
            errorCountryJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(messageJTextField)) {
            errorMessageJLabel.setText("Invalid message value.");
            isValid = false;
        } else {
            errorMessageJLabel.setText("");
        }

        return isValid;
    }

    public void fillFormData(NewEnterpriseWorkRequest newEnterpriseRequest) {
        
        if (networkJComboBox.getSelectedIndex() != -1) {
            selectedNetwork = (Network) networkJComboBox.getSelectedItem();
        }
        Network network = selectedNetwork;
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) enterpriseTypeJComboBox.getSelectedItem();
        newEnterpriseRequest.setNetwork(network);
        Person person = new Person();
        newEnterpriseRequest.setEnterpriseType(type);
        person.setFirstName(firstNameJTextField.getText().trim());
        person.setLastName(lastNameJTextField.getText().trim());
        Contact c = new Contact();
        c.setEmailId(businessEmailIdJTextField.getText());
        c.setPrimaryPhoneNumber(businessPhoneJTextField.getText());
        person.setContact(c);
        Address address = new Address();
        address.setCity(cityJTextField.getText());
        address.setStreet(addressJTextField.getText());
        address.setState(stateJTextField.getText());
        address.setCountry(countryJTextField.getText());
        person.setAddress(address);
        newEnterpriseRequest.setDescription(businessDescriptionJTextArea.getText());
        newEnterpriseRequest.setPerson(person);
        newEnterpriseRequest.setMessage(messageJTextField.getText());
        newEnterpriseRequest.setStatus(WorkRequest.StatusType.ApprovalRequest.getValue());
        newEnterpriseRequest.setEnterpriseName(businessNameJTextField.getText());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JTextArea businessDescriptionJTextArea;
    private javax.swing.JTextField businessEmailIdJTextField;
    private javax.swing.JTextField businessNameJTextField;
    private javax.swing.JTextField businessPhoneJTextField;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JButton closeJButton;
    private javax.swing.JTextField countryJTextField;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JLabel errorAddressJLabel;
    private javax.swing.JLabel errorBussinessNameJLabel;
    private javax.swing.JLabel errorCityJLabel;
    private javax.swing.JLabel errorCountryJLabel;
    private javax.swing.JLabel errorDescriptionJLabel;
    private javax.swing.JLabel errorEmailIdJLabel;
    private javax.swing.JLabel errorEnterpriseJLabel;
    private javax.swing.JLabel errorFirstNameJLabel;
    private javax.swing.JLabel errorLastNameJLabel;
    private javax.swing.JLabel errorMessageJLabel;
    private javax.swing.JLabel errorNetworkJLabel;
    private javax.swing.JLabel errorPhoneJLabel;
    private javax.swing.JLabel errorStateJLabel;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JLabel lblAddressLine3;
    private javax.swing.JLabel lblBusinessCity1;
    private javax.swing.JLabel lblBusinessCountry1;
    private javax.swing.JLabel lblBusinessEmailId3;
    private javax.swing.JLabel lblBusinessName1;
    private javax.swing.JLabel lblBusinessPhone1;
    private javax.swing.JLabel lblBusinessState1;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JTextField stateJTextField;
    private javax.swing.JButton submitRequestJButton;
    // End of variables declaration//GEN-END:variables
}
