/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.distributor;

import business.enterprise.DistributorEnterprise;
import business.workarea.NewDeviceOrderRequest;
import business.workarea.WorkRequest;
import business.workarea.WorkRequest.StatusType;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pu
 */
public class ManageOrderApprovalsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrderApprovalsJPanel
     */
    private JPanel userProcessContainer;
    private DistributorEnterprise enterprise;

    public ManageOrderApprovalsJPanel(JPanel userProcessContainer, DistributorEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) pendingApprovalJTable.getModel();
        dtm.setRowCount(0);
        for (WorkRequest workRequest : enterprise.getWorkQueue().getWorkRequests()) {
            NewDeviceOrderRequest deviceOrderRequest = (NewDeviceOrderRequest) workRequest;

            Object[] rows = new Object[3];
            rows[0] = deviceOrderRequest;
            rows[1] = deviceOrderRequest.getRequestDate();
            rows[2] = deviceOrderRequest.getStatus();

            dtm.addRow(rows);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pendingApprovalJTable = new javax.swing.JTable();
        proceedApproveJButton = new javax.swing.JButton();
        rejectJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        viewOrderDetailsJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        approvalJPanel = new javax.swing.JPanel();
        messageJLabel = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        approveJButton3 = new javax.swing.JButton();
        errorMessageJLabel = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pendingApprovalJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Requested On", "Status"
            }
        ));
        jScrollPane1.setViewportView(pendingApprovalJTable);

        proceedApproveJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        proceedApproveJButton.setText("Proceed to Approve");
        proceedApproveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedApproveJButtonActionPerformed(evt);
            }
        });

        rejectJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rejectJButton.setText("Reject");
        rejectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Order Approvals:");

        viewOrderDetailsJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewOrderDetailsJButton.setText("View/Place Order ");
        viewOrderDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderDetailsJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        approvalJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        approvalJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        messageJLabel.setText("Message:");
        messageJLabel.setEnabled(false);
        approvalJPanel.add(messageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 25));

        messageJTextField.setEnabled(false);
        approvalJPanel.add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 232, 25));

        approveJButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        approveJButton3.setText("Approve");
        approveJButton3.setEnabled(false);
        approveJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButton3ActionPerformed(evt);
            }
        });
        approvalJPanel.add(approveJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 104, -1));

        errorMessageJLabel.setForeground(new java.awt.Color(255, 0, 0));
        approvalJPanel.add(errorMessageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 170, 10));

        refreshJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Device Order Approvals");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(approvalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(backJButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(proceedApproveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(viewOrderDetailsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(refreshJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(rejectJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceedApproveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewOrderDetailsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(approvalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void proceedApproveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedApproveJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = pendingApprovalJTable.getSelectedRow();

        if (selectedRow < 0) {

            JOptionPane.showMessageDialog(null, "Select the request first.");
            return;
        }

        NewDeviceOrderRequest deviceOrderRequest = (NewDeviceOrderRequest) pendingApprovalJTable.getValueAt(selectedRow, 0);

        if (deviceOrderRequest.getStatus().equals(WorkRequest.StatusType.Reject.getValue())) {
            JOptionPane.showMessageDialog(null, "Request already rejected cannnot approve!!.");
            return;
        }

        if (deviceOrderRequest.getStatus().equals(WorkRequest.StatusType.Placed.getValue())) {
            approvalJPanelAction(true);
        } else {
            JOptionPane.showMessageDialog(null, "Order is yet not placed.");
        }


    }//GEN-LAST:event_proceedApproveJButtonActionPerformed

    private void approvalJPanelAction(boolean flag) {
        messageJTextField.setEnabled(flag);
        approveJButton3.setEnabled(flag);
        messageJLabel.setEnabled(flag);
    }

    private void clearFields() {
        messageJTextField.setText("");
    }


    private void rejectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = pendingApprovalJTable.getSelectedRow();

        if (pendingApprovalJTable.getSelectedRowCount() > 0) {

            NewDeviceOrderRequest request = (NewDeviceOrderRequest) pendingApprovalJTable.getValueAt(selectedRow, 0);

            if (request.getStatus().equals(WorkRequest.StatusType.Approved.getValue())) {
                JOptionPane.showMessageDialog(null, "Request already approved cannnot reject!!.");
                return;
            }

            if (request.getStatus().equals(WorkRequest.StatusType.Placed.getValue())) {
                JOptionPane.showMessageDialog(null, "Order placed. cannnot reject.");
                return;
            }

            request.setStatus(WorkRequest.StatusType.Reject.getValue());
            request.getOrder().setStatus(StatusType.Reject.getValue());
            JOptionPane.showMessageDialog(null, "Request rejected successsfully.");
            populateTable();
            
        } else {
            JOptionPane.showMessageDialog(null, "Select the request to be removed.");
        }
    }//GEN-LAST:event_rejectJButtonActionPerformed

    private void viewOrderDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderDetailsJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = pendingApprovalJTable.getSelectedRow();

        if (pendingApprovalJTable.getSelectedRowCount() > 0) {
            NewDeviceOrderRequest request = (NewDeviceOrderRequest) pendingApprovalJTable.getValueAt(selectedRow, 0);

            ViewOrderDetailsJPanel viewOrderDetailsJPanel = new ViewOrderDetailsJPanel(userProcessContainer, enterprise, request);
            userProcessContainer.add("ViewOrderDetailsJPanel", viewOrderDetailsJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Select the request first.");
        }
    }//GEN-LAST:event_viewOrderDetailsJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void approveJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = pendingApprovalJTable.getSelectedRow();

        if (pendingApprovalJTable.getSelectedRowCount() > 0) {
            NewDeviceOrderRequest request = (NewDeviceOrderRequest) pendingApprovalJTable.getValueAt(selectedRow, 0);
            request.setStatus(WorkRequest.StatusType.Approved.getValue());
            request.getOrder().setStatus(StatusType.Approved.getValue());
            approvalJPanelAction(false);
            populateTable();
            clearFields();
        }

    }//GEN-LAST:event_approveJButton3ActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel approvalJPanel;
    private javax.swing.JButton approveJButton3;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel errorMessageJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageJLabel;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTable pendingApprovalJTable;
    private javax.swing.JButton proceedApproveJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton rejectJButton;
    private javax.swing.JButton viewOrderDetailsJButton;
    // End of variables declaration//GEN-END:variables
}
