/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.warehouse;

import business.enterprise.DistributorEnterprise;
import business.model.DeviceMaintenance;
import business.network.Network;
import business.organization.distributor.WarehouseManagementOrganization;
import business.useraccount.UserAccount;
import business.utility.EnumTypes.MaintenanceStatusType;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pu
 */
public class ManageMaintenanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMaintenanceJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DistributorEnterprise enterprise;
    private Network network;
    private WarehouseManagementOrganization organization;
    private ArrayList<DeviceMaintenance> arrayList;

    public ManageMaintenanceJPanel(JPanel userProcessContainer, UserAccount userAccount, DistributorEnterprise enterprise, Network network, WarehouseManagementOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        this.network = network;
        populateStatusComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        devicesUnderMaintenanceJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        updateMaintainJButton = new javax.swing.JButton();
        maintenanceStatusJComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        devicesUnderMaintenanceJTable.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        devicesUnderMaintenanceJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "MaintenanceStart Date", "Maintenance End Date", "Device Category"
            }
        ));
        jScrollPane2.setViewportView(devicesUnderMaintenanceJTable);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Devices under Maintenance:");

        backJButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        updateMaintainJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateMaintainJButton.setText("Update Maintenance");
        updateMaintainJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMaintainJButtonActionPerformed(evt);
            }
        });

        maintenanceStatusJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        maintenanceStatusJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceStatusJComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel4.setText("Select Maintenance Status:");

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Maintenance Of Devices");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(338, 338, 338)
                            .addComponent(updateMaintainJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maintenanceStatusJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintenanceStatusJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateMaintainJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void updateMaintainJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMaintainJButtonActionPerformed
        // TODO add your handling code here:
        if (devicesUnderMaintenanceJTable.getSelectedRowCount() > 0) {
            DeviceMaintenance device = (DeviceMaintenance) devicesUnderMaintenanceJTable.getValueAt(devicesUnderMaintenanceJTable.getSelectedRow(), 0);
            CompleteMaintenanceJPanel viewDevicesJPanel = new CompleteMaintenanceJPanel(userProcessContainer, device);
            userProcessContainer.add("ViewDevicesJPanel", viewDevicesJPanel);
            ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "please select device first.");
        }
    }//GEN-LAST:event_updateMaintainJButtonActionPerformed

    private void maintenanceStatusJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceStatusJComboBoxActionPerformed
        // TODO add your handling code here:
        if (maintenanceStatusJComboBox.getSelectedIndex() != -1) {
            MaintenanceStatusType type = (MaintenanceStatusType) maintenanceStatusJComboBox.getSelectedItem();
            populateMaintainDeviceTable(type);
        }
    }//GEN-LAST:event_maintenanceStatusJComboBoxActionPerformed

    public void populateStatusComboBox() {
        maintenanceStatusJComboBox.removeAllItems();
        maintenanceStatusJComboBox.setModel(new DefaultComboBoxModel(MaintenanceStatusType.values()));
        MaintenanceStatusType type = (MaintenanceStatusType) maintenanceStatusJComboBox.getSelectedItem();
        populateMaintainDeviceTable(type);
    }

    private void populateMaintainDeviceTable(MaintenanceStatusType type) {
        sortOnMaintenanceBasis(type);
        DefaultTableModel model = (DefaultTableModel) devicesUnderMaintenanceJTable.getModel();

        model.setRowCount(0);

        for (DeviceMaintenance device : arrayList) {
            Object[] row = new Object[3];
            row[0] = device;
            row[1] = device.getMaintenanceStartDate();
            row[2] = device.getMaintenanceEndDate();
            row[3] = device.getDevice().getCategory().getCategoryName();
            model.addRow(row);
        }
    }

    public void sortOnMaintenanceBasis(MaintenanceStatusType type) {
        arrayList = new ArrayList<>();
        Date date = new Date();
        for (DeviceMaintenance device : organization.getDeviceMaintenanceCatalog().getDeviceMaintenances()) {
            if (type.getValue().equals("In Future")) {
                if (device.getMaintenanceStartDate().compareTo(date) > 0) {
                    arrayList.add(device);
                    device.setMaintenanceType(type.getValue());
                }
            } else if (type.getValue().equals("Completed")) {
                if (device.getMaintenanceEndDate().compareTo(new Date()) < 0) {
                    arrayList.add(device);
                    device.setMaintenanceType(type.getValue());
                }
            } else {
                arrayList.add(device);
                device.setMaintenanceType(type.getValue());
            }

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable devicesUnderMaintenanceJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox maintenanceStatusJComboBox;
    private javax.swing.JButton updateMaintainJButton;
    // End of variables declaration//GEN-END:variables
}
