/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.warehouse;

import business.model.Device;
import business.utility.EnumTypes;
import business.utility.ValidatingFields;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pu
 */
public class ViewDevicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDevicesJPanel
     */
    private JPanel userProcessContainer;
    private Device device;

    public ViewDevicesJPanel(JPanel userProcessContainer, Device device) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.device = device;
        populateFields();
        populateOperationalStatusBox();
    }

    public void populateFields() {
        deviceIdJTextField.setText(String.valueOf(device.getDeviceId()));
        currentLocationJTextField.setText(device.getCurrentLocation());
        usabilityCountJTextField.setText(String.valueOf(device.getMaxUsabilityCount()));
        reqDescriptionjTextArea.setText(device.getServiceRequirementDescription());
        devicePositionJTextField.setText(device.getDevicePositionInWareHouse());
        operationalStatusJComboBox.setSelectedItem(device.getOperationalStatus());
    }

    public void populateOperationalStatusBox() {
        operationalStatusJComboBox.removeAllItems();
        operationalStatusJComboBox.setModel(new DefaultComboBoxModel(EnumTypes.DeviceStatusType.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        errorDevicepositionJLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reqDescriptionjTextArea = new javax.swing.JTextArea();
        errorOperationalstatusJLabel = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        devicePositionJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        errorServiceReqJLabel = new javax.swing.JLabel();
        errormaxUsabilityJLabel = new javax.swing.JLabel();
        currentLocationJTextField = new javax.swing.JTextField();
        errorCurrentLocationJLabel = new javax.swing.JLabel();
        deviceIdJTextField = new javax.swing.JTextField();
        usabilityCountJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        updateJButton = new javax.swing.JButton();
        operationalStatusJComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Current Location:");

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Device position in Ware House:");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Max Usability Count:");

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("service Requirement \nDescription");

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Device Id:");

        reqDescriptionjTextArea.setColumns(20);
        reqDescriptionjTextArea.setRows(5);
        reqDescriptionjTextArea.setEnabled(false);
        jScrollPane1.setViewportView(reqDescriptionjTextArea);

        errorOperationalstatusJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorOperationalstatusJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorOperationalstatusJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        saveJButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        devicePositionJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        devicePositionJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        devicePositionJTextField.setEnabled(false);

        backJButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        errorServiceReqJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorServiceReqJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorServiceReqJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        errormaxUsabilityJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errormaxUsabilityJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errormaxUsabilityJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        currentLocationJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        currentLocationJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        currentLocationJTextField.setEnabled(false);
        currentLocationJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentLocationJTextFieldActionPerformed(evt);
            }
        });

        errorCurrentLocationJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorCurrentLocationJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorCurrentLocationJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        deviceIdJTextField.setEditable(false);
        deviceIdJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        deviceIdJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        deviceIdJTextField.setEnabled(false);

        usabilityCountJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        usabilityCountJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usabilityCountJTextField.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Operational Status:");

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Device");

        updateJButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        operationalStatusJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(devicePositionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(operationalStatusJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errorDevicepositionJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errorOperationalstatusJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(updateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(usabilityCountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(currentLocationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(deviceIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorServiceReqJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorCurrentLocationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errormaxUsabilityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentLocationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorCurrentLocationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usabilityCountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errormaxUsabilityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorServiceReqJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorDevicepositionJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(devicePositionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorOperationalstatusJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(operationalStatusJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:

        try {

            device.setDevicePositionInWareHouse(devicePositionJTextField.getText());
            device.setMaxUsabilityCount(Integer.parseInt(usabilityCountJTextField.getText()));
            device.setCurrentLocation(currentLocationJTextField.getText());
            device.setServiceRequirementDescription(reqDescriptionjTextArea.getText());
            EnumTypes.DeviceStatusType deviceStatusType = (EnumTypes.DeviceStatusType) operationalStatusJComboBox.getSelectedItem();
            device.setOperationalStatus(deviceStatusType.getValue());
            fieldEnableDisable(false);
            JOptionPane.showMessageDialog(null, "Device updated successfully!!");

        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Enter valid values");
        }
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void currentLocationJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentLocationJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentLocationJTextFieldActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
        fieldEnableDisable(true);
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void fieldEnableDisable(boolean isEnable) {
        currentLocationJTextField.setEnabled(isEnable);
        usabilityCountJTextField.setEnabled(isEnable);
        reqDescriptionjTextArea.setEnabled(isEnable);
        devicePositionJTextField.setEnabled(isEnable);
        operationalStatusJComboBox.setEnabled(isEnable);
        updateJButton.setEnabled(!isEnable);
        saveJButton.setEnabled(isEnable);
    }

    public boolean isValidFieldsValue() {
        boolean isValid = true;

        if (ValidatingFields.isComboBoxValid(operationalStatusJComboBox)) {
            errorOperationalstatusJLabel.setText("Select operational status.");
            isValid = false;
        } else {
            errorOperationalstatusJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(currentLocationJTextField)) {
            errorCurrentLocationJLabel.setText("Enter valid values.");
            isValid = false;
        } else {
            errorCurrentLocationJLabel.setText("");
        }

        if (ValidatingFields.isNumberTextFieldValid(usabilityCountJTextField)) {
            errormaxUsabilityJLabel.setText("Invalid count value.");
            isValid = false;
        } else {
            errormaxUsabilityJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(reqDescriptionjTextArea)) {
            errorServiceReqJLabel.setText("Invalid input string.");
            isValid = false;
        } else {
            errorServiceReqJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(devicePositionJTextField)) {
            errorDevicepositionJLabel.setText("Input valid position.");
            isValid = false;
        } else {
            errorDevicepositionJLabel.setText("");
        }

        return isValid;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField currentLocationJTextField;
    private javax.swing.JTextField deviceIdJTextField;
    private javax.swing.JTextField devicePositionJTextField;
    private javax.swing.JLabel errorCurrentLocationJLabel;
    private javax.swing.JLabel errorDevicepositionJLabel;
    private javax.swing.JLabel errorOperationalstatusJLabel;
    private javax.swing.JLabel errorServiceReqJLabel;
    private javax.swing.JLabel errormaxUsabilityJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox operationalStatusJComboBox;
    private javax.swing.JTextArea reqDescriptionjTextArea;
    private javax.swing.JButton saveJButton;
    private javax.swing.JButton updateJButton;
    private javax.swing.JTextField usabilityCountJTextField;
    // End of variables declaration//GEN-END:variables
}
