/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.warehouse;

import business.Business;
import business.enterprise.DistributorEnterprise;
import business.network.Network;
import business.organization.distributor.WarehouseManagementOrganization;
import business.useraccount.UserAccount;
import business.workarea.NewReservationWorkRequest;
import business.workarea.WorkRequest;
import java.awt.CardLayout;
import java.util.Calendar;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pu
 */
public class WareHouseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WareHouseWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private DistributorEnterprise enterprise;
    private UserAccount userAccount;
    private WarehouseManagementOrganization organization;
    private Business business;
    private Network network;

    public WareHouseWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Network network, DistributorEnterprise enterprise, WarehouseManagementOrganization organization, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        this.organization = organization;
        warehouseJLabel.setText("Welcome "+organization.getOrganizationName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notificationJDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        notificationJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        createCategoryJButton = new javax.swing.JButton();
        manageDevicesJButton = new javax.swing.JButton();
        trackDevicesJButton = new javax.swing.JButton();
        warehouseJLabel = new javax.swing.JLabel();
        orderDeviceRequestJButton = new javax.swing.JButton();
        viewReservationJButton = new javax.swing.JButton();
        notificationsJButton = new javax.swing.JButton();
        manageMaintenanceJButton = new javax.swing.JButton();

        notificationJDialog.setMinimumSize(new java.awt.Dimension(700, 240));

        notificationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reserved On", "Sender", "Start date", "End date", "Device Id", "Reservation Location"
            }
        ));
        jScrollPane1.setViewportView(notificationJTable);

        jLabel2.setText("New Reservations:");

        javax.swing.GroupLayout notificationJDialogLayout = new javax.swing.GroupLayout(notificationJDialog.getContentPane());
        notificationJDialog.getContentPane().setLayout(notificationJDialogLayout);
        notificationJDialogLayout.setHorizontalGroup(
            notificationJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificationJDialogLayout.createSequentialGroup()
                .addGroup(notificationJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notificationJDialogLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(notificationJDialogLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        notificationJDialogLayout.setVerticalGroup(
            notificationJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificationJDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));

        createCategoryJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createCategoryJButton.setText("Manage Category");
        createCategoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCategoryJButtonActionPerformed(evt);
            }
        });

        manageDevicesJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageDevicesJButton.setText("Manage Devices");
        manageDevicesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDevicesJButtonActionPerformed(evt);
            }
        });

        trackDevicesJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        trackDevicesJButton.setText("Track Devices");
        trackDevicesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackDevicesJButtonActionPerformed(evt);
            }
        });

        warehouseJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warehouseJLabel.setText(" Ware House Management");

        orderDeviceRequestJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderDeviceRequestJButton.setText("Order Devices Request");
        orderDeviceRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDeviceRequestJButtonActionPerformed(evt);
            }
        });

        viewReservationJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewReservationJButton.setText("View Reservation");
        viewReservationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReservationJButtonActionPerformed(evt);
            }
        });

        notificationsJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        notificationsJButton.setText("Reservation Notifications");
        notificationsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationsJButtonActionPerformed(evt);
            }
        });

        manageMaintenanceJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageMaintenanceJButton.setText("Manage Maintenance");
        manageMaintenanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMaintenanceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageDevicesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createCategoryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageMaintenanceJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderDeviceRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewReservationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trackDevicesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(warehouseJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(notificationsJButton)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warehouseJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notificationsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createCategoryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(manageDevicesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(orderDeviceRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(manageMaintenanceJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(trackDevicesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(viewReservationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createCategoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCategoryJButtonActionPerformed
        // TODO add your handling code here:
        ManageDevicesCatagoryJPanel manageDevicesCatagoryJPanel = new ManageDevicesCatagoryJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("ManageDevicesCatagoryJPanel", manageDevicesCatagoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createCategoryJButtonActionPerformed

    private void manageDevicesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDevicesJButtonActionPerformed
        // TODO add your handling code here:
        ManageDevicesJPanel manageDevicesJPanel = new ManageDevicesJPanel(userProcessContainer, userAccount, network, enterprise, organization);
        userProcessContainer.add("ManageDevicesJPanel", manageDevicesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDevicesJButtonActionPerformed

    private void trackDevicesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackDevicesJButtonActionPerformed
        // TODO add your handling code here:
        TrackDevicesJPanel trackDevicesJPanel = new TrackDevicesJPanel(userProcessContainer, userAccount, enterprise, network);
        userProcessContainer.add("TrackDevicesJPanel", trackDevicesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_trackDevicesJButtonActionPerformed

    private void orderDeviceRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDeviceRequestJButtonActionPerformed
        // TODO add your handling code here:
        OrderDevicesJPanel orderDevicesJPanel = new OrderDevicesJPanel(userProcessContainer, userAccount, network, enterprise, organization, business);
        userProcessContainer.add("OrderDevicesJPanel", orderDevicesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderDeviceRequestJButtonActionPerformed

    private void viewReservationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReservationJButtonActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_viewReservationJButtonActionPerformed

    private void notificationsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationsJButtonActionPerformed
        // TODO add your handling code here:
        populateTable();
        notificationJDialog.setVisible(true);
    }//GEN-LAST:event_notificationsJButtonActionPerformed

    private void manageMaintenanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMaintenanceJButtonActionPerformed
        // TODO add your handling code here:
        MaintainDeviceJPanel maintainDeviceJPanel = new MaintainDeviceJPanel(userProcessContainer, userAccount, enterprise, network, organization);
        userProcessContainer.add("MaintainDeviceJPanel", maintainDeviceJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageMaintenanceJButtonActionPerformed

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) notificationJTable.getModel();
        dtm.setRowCount(0);
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DATE, -2);
        for (WorkRequest workRequest : organization.getWorkQueue().getWorkRequests()) {
            NewReservationWorkRequest reservationWorkRequest = (NewReservationWorkRequest) workRequest;
            if ((reservationWorkRequest.getRequestDate().compareTo(cal.getTime()) > 0)
                    || (reservationWorkRequest.getRequestDate().compareTo(cal.getTime()) == 0)) {
                Object[] rows = new Object[6];
                rows[0] = reservationWorkRequest.getRequestDate();
                rows[1] = reservationWorkRequest.getSender().getUserName();
                rows[2] = reservationWorkRequest.getReservation().getStartTime();
                rows[3] = reservationWorkRequest.getReservation().getEndTime();
                rows[4] = reservationWorkRequest.getReservation().getDevice().getDeviceId();
                rows[5] = reservationWorkRequest.getReservation().getLocation();

                dtm.addRow(rows);
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createCategoryJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageDevicesJButton;
    private javax.swing.JButton manageMaintenanceJButton;
    private javax.swing.JDialog notificationJDialog;
    private javax.swing.JTable notificationJTable;
    private javax.swing.JButton notificationsJButton;
    private javax.swing.JButton orderDeviceRequestJButton;
    private javax.swing.JButton trackDevicesJButton;
    private javax.swing.JButton viewReservationJButton;
    private javax.swing.JLabel warehouseJLabel;
    // End of variables declaration//GEN-END:variables
}
