/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.hospital;

import business.Business;
import business.enterprise.HospitalEnterprise;
import business.network.Network;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.distributor.ManageOrganizationJPanel;
import userinterface.distributor.ManageUserAccountJPanel;

/**
 *
 * @author pu
 */
public class HospitalWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private HospitalEnterprise enterprise;
    private Network network;
    private UserAccount userAccount;
    private Business business;

    public HospitalWorkAreaJPanel(JPanel userProcessContainer, Network network, HospitalEnterprise enterprise, UserAccount userAccount, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.userAccount = userAccount;
        this.business = business;
        hospJLabel.setText(enterprise.getOrganizationName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospJLabel = new javax.swing.JLabel();
        createOrganizationJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        userAccountJButton = new javax.swing.JButton();
        manageApprovalsJButton = new javax.swing.JButton();
        manageOperationalRoomsJButton = new javax.swing.JButton();
        manageSurgeryTypeJButton = new javax.swing.JButton();
        manageOperationalTeamsJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        hospJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hospJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospJLabel.setText("Welcome hospital");

        createOrganizationJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createOrganizationJButton.setText("Create Organization");
        createOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOrganizationJButtonActionPerformed(evt);
            }
        });

        manageOrganizationJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });

        userAccountJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userAccountJButton.setText("User Account");
        userAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAccountJButtonActionPerformed(evt);
            }
        });

        manageApprovalsJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageApprovalsJButton.setText("Manage Approvals");
        manageApprovalsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageApprovalsJButtonActionPerformed(evt);
            }
        });

        manageOperationalRoomsJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageOperationalRoomsJButton.setText("Manage Operational Rooms");
        manageOperationalRoomsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOperationalRoomsJButtonActionPerformed(evt);
            }
        });

        manageSurgeryTypeJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageSurgeryTypeJButton.setText("Manage Surgery Type");
        manageSurgeryTypeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSurgeryTypeJButtonActionPerformed(evt);
            }
        });

        manageOperationalTeamsJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageOperationalTeamsJButton.setText("Manage Operational Teams");
        manageOperationalTeamsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOperationalTeamsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageApprovalsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageOperationalRoomsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageSurgeryTypeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageOperationalTeamsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(hospJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(284, 284, 284))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(hospJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(createOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(userAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(manageApprovalsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(manageOperationalRoomsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(manageSurgeryTypeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(manageOperationalTeamsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        CreateOrganizationJPanel createOrganizationJPanel = new CreateOrganizationJPanel(userProcessContainer,network,enterprise);
        userProcessContainer.add("CreateOrganizationJPanel", createOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createOrganizationJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("ManageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void userAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAccountJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel manageUserAccountJPanel = new ManageUserAccountJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), business);
        userProcessContainer.add("ManageUserAccountJPanel", manageUserAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userAccountJButtonActionPerformed

    private void manageApprovalsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageApprovalsJButtonActionPerformed
        // TODO add your handling code here:
        ManageSurgeryApprovalsJPanel manageSurgeryApprovalsJPanel = new ManageSurgeryApprovalsJPanel(userProcessContainer, network, enterprise, userAccount);
        userProcessContainer.add("ManageSurgeryApprovalsJPanel", manageSurgeryApprovalsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageApprovalsJButtonActionPerformed

    private void manageOperationalRoomsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOperationalRoomsJButtonActionPerformed
        // TODO add your handling code here:
        ManageOperationalRoomsJPanel manageOperationalRoomsJPanel = new ManageOperationalRoomsJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageOperationalRoomsJPanel", manageOperationalRoomsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOperationalRoomsJButtonActionPerformed

    private void manageSurgeryTypeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSurgeryTypeJButtonActionPerformed
        // TODO add your handling code here:
        ManageSurgeryTypeJPanel manageSurgeryTypeJPanel = new ManageSurgeryTypeJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageSurgeryTypeJPanel", manageSurgeryTypeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageSurgeryTypeJButtonActionPerformed

    private void manageOperationalTeamsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOperationalTeamsJButtonActionPerformed
        // TODO add your handling code here:
        ManageSurgeryTeamJPanel manageSurgeryTeamJPanel = new ManageSurgeryTeamJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageSurgeryTeamJPanel", manageSurgeryTeamJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOperationalTeamsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createOrganizationJButton;
    private javax.swing.JLabel hospJLabel;
    private javax.swing.JButton manageApprovalsJButton;
    private javax.swing.JButton manageOperationalRoomsJButton;
    private javax.swing.JButton manageOperationalTeamsJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton manageSurgeryTypeJButton;
    private javax.swing.JButton userAccountJButton;
    // End of variables declaration//GEN-END:variables
}
