/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.supplier;

import business.enterprise.SupplierEnterprise;
import business.model.Product;
import business.utility.ValidatingFields;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pu
 */
public class CreateProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateProductJPanel
     */
    private SupplierEnterprise supplierEnterprise;
    private ManageProductCatalogJPanel manageProductCatalogJPanel;
    private JPanel userProcessContainer;

    public CreateProductJPanel(JPanel userProcessContainer, SupplierEnterprise supplierEnterprise, ManageProductCatalogJPanel manageProductCatalogJPanel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierEnterprise = supplierEnterprise;
        this.manageProductCatalogJPanel = manageProductCatalogJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        priceJTextField = new javax.swing.JTextField();
        ProductIdJTextField = new javax.swing.JTextField();
        productNameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AddProductJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        errorAvailabilityJLabel = new javax.swing.JLabel();
        errorPriceJLabel = new javax.swing.JLabel();
        errorProductNameJLabel = new javax.swing.JLabel();
        availabilityJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        errorWarrantyPeriodJLabel = new javax.swing.JLabel();
        serialNumbeJTextField = new javax.swing.JTextField();
        errorSerialNumberJLabel = new javax.swing.JLabel();
        modelNumberJTextField = new javax.swing.JTextField();
        errorManufacturerNameJLabel = new javax.swing.JLabel();
        manufacturerNameJTextField = new javax.swing.JTextField();
        warrentyPeriodJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        errorModelNumberJLabel = new javax.swing.JLabel();
        errorProductFeaturesJLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productFeaturesJTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        priceJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        priceJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        priceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceJTextFieldActionPerformed(evt);
            }
        });

        ProductIdJTextField.setEditable(false);
        ProductIdJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        ProductIdJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ProductIdJTextField.setEnabled(false);

        productNameJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        productNameJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Price:");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Availability:");

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Product Id:");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Product Name:");

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create New Product");

        AddProductJButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        AddProductJButton.setText("Add Product");
        AddProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        errorAvailabilityJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorAvailabilityJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorAvailabilityJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        errorPriceJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorPriceJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorPriceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        errorProductNameJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorProductNameJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorProductNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        availabilityJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        availabilityJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(" Model Number:");

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Manufacturer Name:");

        errorWarrantyPeriodJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorWarrantyPeriodJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorWarrantyPeriodJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        serialNumbeJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        serialNumbeJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        serialNumbeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumbeJTextFieldActionPerformed(evt);
            }
        });

        errorSerialNumberJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorSerialNumberJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorSerialNumberJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        modelNumberJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        modelNumberJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        errorManufacturerNameJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorManufacturerNameJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorManufacturerNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        manufacturerNameJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        manufacturerNameJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        warrentyPeriodJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        warrentyPeriodJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Serial Number:");

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Warranty Period (in months):");

        errorProductFeaturesJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorProductFeaturesJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorProductFeaturesJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel11.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Product Features:");

        productFeaturesJTextArea.setColumns(20);
        productFeaturesJTextArea.setRows(5);
        jScrollPane1.setViewportView(productFeaturesJTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(manufacturerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(warrentyPeriodJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(serialNumbeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(modelNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddProductJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(errorSerialNumberJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                        .addComponent(errorWarrantyPeriodJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                        .addComponent(errorManufacturerNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                        .addComponent(errorModelNumberJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(errorProductFeaturesJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(ProductIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(productNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(availabilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(priceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(errorPriceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(errorAvailabilityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(errorProductNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorProductNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorPriceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availabilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorAvailabilityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorManufacturerNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorModelNumberJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNumbeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorSerialNumberJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warrentyPeriodJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorWarrantyPeriodJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorProductFeaturesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddProductJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void priceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceJTextFieldActionPerformed

    private void AddProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductJButtonActionPerformed
        // TODO add your handling code here:
        if (isValidData()) {
            try {
                Product product = supplierEnterprise.getProductCatalog().addProduct();
                product.setName(productNameJTextField.getText());
                product.setPrice(Double.parseDouble(priceJTextField.getText()));
                product.setAvailability(Integer.parseInt(availabilityJTextField.getText()));
                product.setSoldQuantity(Integer.parseInt(availabilityJTextField.getText()));
                product.setFeatures(productFeaturesJTextArea.getText());
                product.setManufacturer(manufacturerNameJTextField.getText());
                product.setModelNumber(modelNumberJTextField.getText());
                product.setSerialNumber(serialNumbeJTextField.getText());
                product.setWarrantyPeriod(Integer.parseInt(warrentyPeriodJTextField.getText()));
                ProductIdJTextField.setText(String.valueOf(product.getProductId()));
                JOptionPane.showMessageDialog(null, "Product added successfully!!");
                manageProductCatalogJPanel.populateTable();

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(null, "Enter valid values");
            }
        }
    }//GEN-LAST:event_AddProductJButtonActionPerformed

    private boolean isValidData() {
        boolean isValidValue = true;

        if (ValidatingFields.isNumberTextFieldValid(availabilityJTextField)) {
            errorAvailabilityJLabel.setText("Enter valid numeric value.");
            isValidValue = false;
        } else {
            errorAvailabilityJLabel.setText("");
        }

        if (ValidatingFields.isIntegerTextFieldValid(priceJTextField)) {
            errorPriceJLabel.setText("Enter valid numeric value.");
            isValidValue = false;
        } else {
            errorPriceJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(productNameJTextField)) {
            errorProductNameJLabel.setText("Name contains only alphabest and numbers");
            isValidValue = false;
        } else {
            errorProductNameJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(manufacturerNameJTextField)) {
            errorManufacturerNameJLabel.setText("Name contains only alphabest and numbers");
            isValidValue = false;
        } else {
            errorManufacturerNameJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(modelNumberJTextField)) {
            errorModelNumberJLabel.setText("Name contains only alphabest and numbers");
            isValidValue = false;
        } else {
            errorModelNumberJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(serialNumbeJTextField)) {
            errorSerialNumberJLabel.setText("Name contains only alphabest and numbers");
            isValidValue = false;
        } else {
            if (!supplierEnterprise.getProductCatalog().isUniqueSerialNumber(serialNumbeJTextField.getText())) {
                errorSerialNumberJLabel.setText("SerialNumber already exist.");
                isValidValue = false;
            } else {
                errorSerialNumberJLabel.setText("");
            }
        }

        if (ValidatingFields.isNumberTextFieldValid(warrentyPeriodJTextField)) {
            errorWarrantyPeriodJLabel.setText("Enter valid numeric value.");
            isValidValue = false;
        } else {
            errorWarrantyPeriodJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(productFeaturesJTextArea)) {
            errorProductFeaturesJLabel.setText("Features contains only alphabest and numbers");
            isValidValue = false;
        } else {
            errorProductFeaturesJLabel.setText("");
        }

        return isValidValue;
    }

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void serialNumbeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumbeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumbeJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductJButton;
    private javax.swing.JTextField ProductIdJTextField;
    private javax.swing.JTextField availabilityJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel errorAvailabilityJLabel;
    private javax.swing.JLabel errorManufacturerNameJLabel;
    private javax.swing.JLabel errorModelNumberJLabel;
    private javax.swing.JLabel errorPriceJLabel;
    private javax.swing.JLabel errorProductFeaturesJLabel;
    private javax.swing.JLabel errorProductNameJLabel;
    private javax.swing.JLabel errorSerialNumberJLabel;
    private javax.swing.JLabel errorWarrantyPeriodJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField manufacturerNameJTextField;
    private javax.swing.JTextField modelNumberJTextField;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JTextArea productFeaturesJTextArea;
    private javax.swing.JTextField productNameJTextField;
    private javax.swing.JTextField serialNumbeJTextField;
    private javax.swing.JTextField warrentyPeriodJTextField;
    // End of variables declaration//GEN-END:variables
}
