/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.supplier;

import business.enterprise.SupplierEnterprise;
import business.model.Product;
import business.utility.ValidatingFields;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pu
 */
public class ViewProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewProductJPanel
     */
    private JPanel userProcessContainerJPanel;
    private Product product;
    private SupplierEnterprise supplierEnterprise;

    public ViewProductJPanel(JPanel userProcessContainerJPanel, Product product, SupplierEnterprise supplierEnterprise) {
        initComponents();
        this.userProcessContainerJPanel = userProcessContainerJPanel;
        this.product = product;
        this.supplierEnterprise = supplierEnterprise;
        populateFields();
    }

    private void populateFields() {
        saveJButton.setEnabled(false);
        productNameJTextField.setText(product.getName());
        priceJTextField.setText(String.valueOf(product.getPrice()));
        productIdJTextField.setText(String.valueOf(product.getProductId()));
        productFeatureJTextArea.setText(product.getFeatures());
        manufacturerNameJTextField.setText(product.getManufacturer());
        serialNumbeJTextField.setText(product.getSerialNumber());
        modelNumberJTextField.setText(product.getModelNumber());
        warrentyPeriodJTextField.setText(String.valueOf(product.getWarrantyPeriod()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        errorPriceJLabel = new javax.swing.JLabel();
        errorProductNameJLabel = new javax.swing.JLabel();
        updateProductJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        priceJTextField = new javax.swing.JTextField();
        productIdJTextField = new javax.swing.JTextField();
        productNameJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        errorModelNumberJLabel = new javax.swing.JLabel();
        errorProductFeaturesJLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        errorWarrantyPeriodJLabel = new javax.swing.JLabel();
        serialNumbeJTextField = new javax.swing.JTextField();
        errorSerialNumberJLabel = new javax.swing.JLabel();
        modelNumberJTextField = new javax.swing.JTextField();
        errorManufacturerNameJLabel = new javax.swing.JLabel();
        manufacturerNameJTextField = new javax.swing.JTextField();
        warrentyPeriodJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productFeatureJTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Product Details");

        errorPriceJLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorPriceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        errorProductNameJLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorProductNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        updateProductJButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        updateProductJButton.setText("Update Product");
        updateProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductJButtonActionPerformed(evt);
            }
        });

        saveJButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        saveJButton.setText("Save");
        saveJButton.setEnabled(false);
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        priceJTextField.setEditable(false);
        priceJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        priceJTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        productIdJTextField.setEditable(false);
        productIdJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        productIdJTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        productIdJTextField.setEnabled(false);

        productNameJTextField.setEditable(false);
        productNameJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        productNameJTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Product ID:");

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Price:");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Product Name:");

        errorProductFeaturesJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorProductFeaturesJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorProductFeaturesJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel11.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Product Features:");

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(" Model Number:");

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Manufacturer Name:");

        errorWarrantyPeriodJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorWarrantyPeriodJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorWarrantyPeriodJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        serialNumbeJTextField.setEditable(false);
        serialNumbeJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        serialNumbeJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        serialNumbeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumbeJTextFieldActionPerformed(evt);
            }
        });

        errorSerialNumberJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorSerialNumberJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorSerialNumberJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        modelNumberJTextField.setEditable(false);
        modelNumberJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        modelNumberJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        errorManufacturerNameJLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        errorManufacturerNameJLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorManufacturerNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        manufacturerNameJTextField.setEditable(false);
        manufacturerNameJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        manufacturerNameJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        warrentyPeriodJTextField.setEditable(false);
        warrentyPeriodJTextField.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        warrentyPeriodJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Serial Number:");

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Warranty Period (in months):");

        productFeatureJTextArea.setColumns(20);
        productFeatureJTextArea.setRows(5);
        productFeatureJTextArea.setEnabled(false);
        jScrollPane1.setViewportView(productFeatureJTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231)
                        .addComponent(errorProductFeaturesJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(updateProductJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(warrentyPeriodJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(serialNumbeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(modelNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(20, 20, 20)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(manufacturerNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                .addComponent(productNameJTextField)
                                                .addComponent(priceJTextField)
                                                .addComponent(productIdJTextField)))))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(errorProductNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errorPriceJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(errorSerialNumberJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(errorWarrantyPeriodJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(errorManufacturerNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(errorModelNumberJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, 0)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorProductNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(errorPriceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorManufacturerNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorModelNumberJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNumbeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorSerialNumberJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warrentyPeriodJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorWarrantyPeriodJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorProductFeaturesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateProductJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductJButtonActionPerformed
        // TODO add your handling code here:
        enableDisbleFields(true);
    }//GEN-LAST:event_updateProductJButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:

        try {
            if (isValidData()) {
                product.setName(productNameJTextField.getText());
                product.setPrice(Double.parseDouble(priceJTextField.getText()));
                product.setFeatures(productFeatureJTextArea.getText());
                product.setManufacturer(manufacturerNameJTextField.getText());
                product.setModelNumber(modelNumberJTextField.getText());
                product.setSerialNumber(serialNumbeJTextField.getText());
                product.setWarrantyPeriod(Integer.parseInt(warrentyPeriodJTextField.getText()));
                enableDisbleFields(false);
                JOptionPane.showMessageDialog(null, "Updated successfully!!");
            }
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Invalid input");
        }
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void enableDisbleFields(boolean flag) {
        saveJButton.setEnabled(flag);
        productNameJTextField.setEditable(flag);
        priceJTextField.setEditable(flag);
        updateProductJButton.setEnabled(!flag);
        manufacturerNameJTextField.setEditable(flag);
        warrentyPeriodJTextField.setEditable(flag);
        modelNumberJTextField.setEditable(flag);
        serialNumbeJTextField.setEditable(flag);
        productFeatureJTextArea.setEditable(flag);
    }

    private boolean isValidData() {
        boolean isValidValue = true;

        if (ValidatingFields.isIntegerTextFieldValid(priceJTextField)) {
            errorPriceJLabel.setText("Enter valid numeric value.");
            isValidValue = false;
        } else {
            errorPriceJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(productNameJTextField)) {
            errorProductNameJLabel.setText("Name contains only alphabest and numbers");
            isValidValue = false;
        } else {
            errorProductNameJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(manufacturerNameJTextField)) {
            errorManufacturerNameJLabel.setText("Name contains only alphabest and numbers");
            isValidValue = false;
        } else {
            errorManufacturerNameJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(modelNumberJTextField)) {
            errorModelNumberJLabel.setText("Name contains only alphabest and numbers");
            isValidValue = false;
        } else {
            errorModelNumberJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(serialNumbeJTextField)) {
            errorSerialNumberJLabel.setText("Name contains only alphabest and numbers");
            isValidValue = false;
        } else {
            if (!product.getSerialNumber().equalsIgnoreCase(serialNumbeJTextField.getText())) {
                if (!supplierEnterprise.getProductCatalog().isUniqueSerialNumber(serialNumbeJTextField.getText())) {
                    errorSerialNumberJLabel.setText("SerialNumber already exist.");
                    isValidValue = false;
                } else {
                    errorSerialNumberJLabel.setText("");
                }
            } else {
                errorSerialNumberJLabel.setText("");
            }
        }

        if (ValidatingFields.isNumberTextFieldValid(warrentyPeriodJTextField)) {
            errorWarrantyPeriodJLabel.setText("Enter valid numeric value.");
            isValidValue = false;
        } else {
            errorWarrantyPeriodJLabel.setText("");
        }

        if (ValidatingFields.isStringTextFieldValid(productFeatureJTextArea)) {
            errorProductFeaturesJLabel.setText("Features contains only alphabest and numbers");
            isValidValue = false;
        } else {
            errorProductFeaturesJLabel.setText("");
        }

        return isValidValue;
    }

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainerJPanel.remove(this);
        CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
        layout.previous(userProcessContainerJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void serialNumbeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumbeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumbeJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel errorManufacturerNameJLabel;
    private javax.swing.JLabel errorModelNumberJLabel;
    private javax.swing.JLabel errorPriceJLabel;
    private javax.swing.JLabel errorProductFeaturesJLabel;
    private javax.swing.JLabel errorProductNameJLabel;
    private javax.swing.JLabel errorSerialNumberJLabel;
    private javax.swing.JLabel errorWarrantyPeriodJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField manufacturerNameJTextField;
    private javax.swing.JTextField modelNumberJTextField;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JTextArea productFeatureJTextArea;
    private javax.swing.JTextField productIdJTextField;
    private javax.swing.JTextField productNameJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JTextField serialNumbeJTextField;
    private javax.swing.JButton updateProductJButton;
    private javax.swing.JTextField warrentyPeriodJTextField;
    // End of variables declaration//GEN-END:variables
}
